### ISSUE TITLE
MQTT name, password, secure connection

### ISSUE THREAD

**Issue by joysfera** [bastlirna/mqtt-wall#25]
Please provide an example in index.html with name and password for connecting to MQTT broker and also a flag to enforce secure (TLS encrypted) connection. Thanks! :)

**Comment by ah01** [comment]
It was not possible till now. Thx for hint :smile:

*Example settings:*

```javascript
server: {
  uri: "wss://example.org/mqtt", // <-- wss (for secured websockets)
  username: "tester", 
  password: "cGFzc3dvcmQ=" // <-- string "password" in base46
}
```

See [comment in settings](https://github.com/bastlirna/mqtt-wall/blob/master/src/index.html#L28) for detail.

**Comment by joysfera** [comment]
Thanks for after-midnight fix :)
